# _

In [43]:
def get_mean(arr):
    _sum = 0
    for ele in arr:
        # _sum = _sum + ele
        _sum += ele
    _mean = _sum/len(arr)
    return _mean

In [2]:
l1 = [1,2,3,4,5,6]

In [3]:
get_mean(l1)

3.5

In [44]:
import math
def get_median(arr):
    sorted_arr = sorted(arr)
    n = len(arr)
    if n % 2 == 0:
        idx1 = int(n/2)
        idx2 = idx1 - 1
        _median = get_mean([arr[idx1],arr[idx2]])
        return _median
    else:
        idx = math.floor(n/2)
        _median = arr[idx]
        return _median

In [11]:
get_median(l1)

3.5

In [9]:
l2 = [1,2,3,4,5]

In [12]:
get_median(l2)

3

In [14]:
l3 = [1,2,3,3,2,3,1]
# {1:2,2:2,3:3}
# {2:1,2:2,3:3}

In [25]:
dict_ = {}
for i in l3:
    dict_[i] = 0

In [26]:
dict_

{1: 0, 2: 0, 3: 0}

In [27]:
for i in range(len(l3)):
    count_ = 0
    for j in range(len(l3)):
        if l3[i] == l3[j]:
            count_ += 1
    dict_[l3[i]] = count_

In [28]:
dict_

{1: 2, 2: 2, 3: 3}

In [45]:
## last frequency element will be updated
def get_mode(arr):
    dict_ = {}
    for i in arr:
        dict_[i] = 0
    for i in range(len(arr)):
        count_ = 0
        for j in range(len(arr)):
            if arr[i] == arr[j]:
                count_ += 1
        dict_[arr[i]] = count_
    new_dict = {value:key for key,value in dict_.items()}
    high_frequency = max(new_dict)
    mode_ = new_dict[high_frequency]
    return mode_

In [30]:
get_mode(l3)

3

In [34]:
l4 = [1,2,2,3,3,4]
{1:0,2:0,3:0,4:0}
{1:1,2:2,3:2,4:1}
{1:1,2:2,2:3,1:4}
{1:4,2:3}

{1: 4, 2: 3}

In [33]:
get_mode(l4)

3

In [68]:
import numpy

In [72]:
arr1 = numpy.arange(100000000)

In [74]:
import time
first = time.time()
get_mean(arr1)
second = time.time()
second-first

4.293209791183472

In [73]:
import time
first = time.time()
numpy.mean(arr1)
second = time.time()
second-first

0.34595203399658203

In [51]:
numpy.mean(arr1)

499999999.5

In [47]:
get_median(arr1)

499.5

In [48]:
get_mode(arr1)

999

In [75]:
class MatrixAdditionError(Exception):
    pass
    
class NewList(list):
    def __init__(self,l):
        super().__init__()
        self.list = list(l)
    def __add__(self,other):
        if len(self.list) == len(other.list):
            new_list = []
            for i in range(len(self.list)):
                new_list.append(self.list[i]+other.list[i])
            return new_list
        else:
            raise MatrixAdditionError("Addition is applicable only on same sized lists")

In [1]:
arr1 = numpy.arange(100000000)
arr2 = numpy.arange(200000000,300000000)

NameError: name 'numpy' is not defined

In [ ]:
custom_list1 = NewList(arr1)

In [ ]:
custom_list2 = NewList(arr2)

In [123]:
import time
first = time.time()
result_from_list = custom_list1 + custom_list2
second = time.time()
print(second-first)

In [124]:
result_from_numpy = arr1 + arr2

In [1]:
import numpy

In [23]:
A = numpy.random.rand(3,3)

In [24]:
m,n = A.shape

In [25]:
B = numpy.random.rand(3,3)

In [26]:
p,q = B.shape

In [31]:
C = numpy.zeros((3,3))

In [32]:
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:

if n == p:
    #traversing rows in first matrix.. i is pointing to first row of A
    for i in range(m):
        #traversing columns in second matrix.. j is pointing to first column of B
        for j in range(q):
            #traversing column wise for rows of first matrix and row wise for columns of second matrix
            for k in range(n):
                C[i][j] += A[i,k] * B[k,j]

In [30]:
C

array([[0.51491804, 0.38492743, 0.5362276 ],
       [0.47518581, 0.43131922, 0.58190566],
       [0.72309847, 0.65218446, 0.91559034]])

In [15]:
# Time complexity of above algorithm.
# m*q*n
# n**3

In [43]:
for i in range(m):
    for j in range(q):
        # We removed traversal of elements and replaced with numpy vectorized multiplication.
        C[i][j] = numpy.sum(A[i]*B.T[j])
# Time complexity is now m*q --> n**2

In [41]:
sum(A[0]*B[0])

0.8954229158051901

In [36]:
x = A[0]

In [37]:
y = B[0]

In [38]:
x

array([0.54122771, 0.70712468, 0.261869  ])

In [39]:
y

array([0.5712247 , 0.54078366, 0.7784763 ])

In [42]:
C

array([[0.51491804, 0.38492743, 0.5362276 ],
       [0.47518581, 0.43131922, 0.58190566],
       [0.72309847, 0.65218446, 0.91559034]])

In [10]:
def matmul_1(A,B,C):
    m,n = A.shape
    p,q = B.shape
    if n == p:
        #traversing rows in first matrix.. i is pointing to first row of A
        for i in range(m):
            #traversing columns in second matrix.. j is pointing to first column of B
            for j in range(q):
                #traversing column wise for rows of first matrix and row wise for columns of second matrix
                for k in range(n):
                    C[i][j] += A[i,k] * B[k,j]

In [3]:
import numpy as np

In [4]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [5]:
m,n = A.shape # tuple unpacking
p,q = B.shape 

In [6]:
C = np.zeros((m,q))

In [7]:
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
matmul_1(A,B,C)

In [12]:
C

array([[1.52580228, 0.7921754 , 1.78429049],
       [0.48193594, 0.24161095, 0.96216304],
       [2.42142664, 1.34811878, 1.38784783]])

In [18]:
def matmul_2(A,B,C):
    m = A.shape[0]
    q = B.shape[1]
    for i in range(m):
        for j in range(q):
            # We removed traversal of elements and replaced with numpy vectorized multiplication.
            C[i][j] = np.sum(A[i]*B.T[j])
    # Time complexity is now m*q --> n**2

In [19]:
matmul_2(A,B,C)

In [20]:
C

array([[0.76290114, 0.3960877 , 0.89214525],
       [0.24096797, 0.12080548, 0.48108152],
       [1.21071332, 0.67405939, 0.69392392]])

In [35]:
import time
size = (1000,1000)
A = np.random.rand(*size)
B = np.random.rand(*size)
C = np.zeros(size)

In [36]:
first = time.time()
matmul_1(A,B,C) # Inefficient
second = time.time()
second-first

KeyboardInterrupt: 

In [37]:
first = time.time()
matmul_2(A,B,C) # Little bit Efficient
second = time.time()
second-first

2.8787729740142822

In [38]:
first = time.time()
C = np.dot(A,B) # More Efficient
second = time.time()
second-first

0.06444406509399414

In [2]:
import numpy as np
A = np.random.rand(2,2)
B = np.random.rand(2,2)

In [3]:
A < B

array([[ True,  True],
       [False,  True]])

In [4]:
A

array([[0.06625365, 0.21626026],
       [0.65789018, 0.6388289 ]])

In [5]:
B

array([[0.57537783, 0.37905597],
       [0.11139739, 0.64272824]])

In [7]:
np.less(A,B)

array([[ True,  True],
       [False,  True]])

In [8]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [9]:
A = np.arange(0,10000)

In [10]:
A.shape

(10000,)

In [11]:
A.ndim

1

In [12]:
B = np.reshape(A,(100,100))

In [13]:
B.shape

(100, 100)

In [14]:
B.ndim

2

In [15]:
C = np.reshape(A,(10,10,10,10))

In [16]:
C.shape

(10, 10, 10, 10)

In [17]:
C.ndim

4

In [18]:
A

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [21]:
B[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
C.shape

(10, 10, 10, 10)

In [24]:
C[0].shape

(10, 10, 10)

In [27]:
# Image Processing & Transformers.

array([[[3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009],
        [3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019],
        [3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029],
        [3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039],
        [3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049],
        [3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059],
        [3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069],
        [3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079],
        [3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089],
        [3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099]],

       [[3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109],
        [3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119],
        [3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129],
        [3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139],
        [3140, 314

In [28]:
A = np.arange(10)

In [46]:
B = np.arange(11,21)

In [42]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
B

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
A.shape

(10,)

In [48]:
B.shape

(10,)

In [59]:
np.concatenate((A,B),axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
A_ = np.reshape(A,(2,5))
B_ = np.reshape(B,(2,5))

In [63]:
A_

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
B_

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [65]:
np.concatenate((A_,B_),axis=0) # column-wise  ## Operations done row-by-row

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [72]:
np.concatenate((A_,B_),axis=1) # row-wise #$ Operations done column-by-column
## Concatenation will not create a new dimension.

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [68]:
A_

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
B_

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
C_ = np.stack((A_,B_)) ## Stacking create a new dimension

In [74]:
C_

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [75]:
C_.shape

(2, 2, 5)

In [3]:
import numpy as np

In [4]:
A = np.arange(0,100)

In [5]:
A.shape

(100,)

In [6]:
A.ndim

1

In [7]:
A.size

100

In [8]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
A_ = np.reshape(A,(10,10))

In [11]:
A_.shape

(10, 10)

In [12]:
A_.size

100

In [13]:
A_.ndim

2

In [18]:
flattened_A = A_.flatten()

In [16]:
A_

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
raveled_A = A_.ravel()

In [21]:
flattened_A[0] = 100

In [22]:
A_

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
raveled_A[0] = 100

In [24]:
A_

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [25]:
A = [2,4,6,8]

In [26]:
even_numbers = np.array(A)

In [33]:
(even_numbers % 2).all()

False

In [34]:
(even_numbers % 2).any()

False

In [39]:
any(([True, False, False]))

True

In [40]:
np.array([True, False, False]).all()

False

In [41]:
A

[2, 4, 6, 8]

In [42]:
A_ = np.array(A)

In [44]:
A_

array([2, 4, 6, 8])

In [50]:
A_

array([2, 4, 6, 8])

In [51]:
np.min(A_)

2

2